minecraft_proxy:
  container_name: gs_mc_proxy
  image:  itzg/bungeecord:latest
  enviroment:
    UID:  1000
    GID:  1000
    TYPE: WATERFALL
    MEMORY: 1024M
  restart:  unless-stopped
  ports:
    - 25565:25577
  
  volumes:
    - /mnt/user/appdata/gs_mc_proxy:/server

