version: "3.8"
services:
  proxy:
    image: itzg/bungeecord
    name: gs_mc_proxy
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TYPE: WATERFALL
      WATERFALL_VERSION:  latest
      WATERFALL_BUILD_ID: latest
      MEMORY: 512m
      INIT_MEMORY:  1024m
      MAX_MEMORY: 2048m
      NETWORKADDRESS_CACHE_TTL: 60
      HEALTH_HOST: localhost
      REPLACE_ENV_DURING_SYNC:  true
      MOTD: "LOOYN-ARCADE PTR"

    ports:
      - "25565:25577"
    volumes:
      - /mnt/user/appdata/gs_mc_proxy:/server
